version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - CORS_ORIGIN=http://localhost:3000
    volumes:
      - ./backend:/app/backend
      - ./frontend:/app/frontend
    command: ["npm", "run", "dev:backend"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    ports:
      - "3000:3000"
    environment:
      - VITE_API_BASE_URL=http://localhost:3001
      - VITE_WS_URL=ws://localhost:3001
    volumes:
      - ./frontend:/app/frontend
    command: ["npm", "run", "dev:frontend"]
    depends_on:
      - backend

  # Development setup
  dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    ports:
      - "3000:3000"
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
      - CORS_ORIGIN=http://localhost:3000
      - VITE_API_BASE_URL=http://localhost:3001
      - VITE_WS_URL=ws://localhost:3001
    volumes:
      - .:/app
      - /app/node_modules
      - /app/backend/node_modules
      - /app/frontend/node_modules
    command: ["npm", "run", "dev"]
    working_dir: /app

