name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Lint backend
      run: npm run lint:backend

    - name: Lint frontend
      run: npm run lint:frontend

    - name: Test backend
      run: npm run test:backend

    - name: Test frontend
      run: npm run test:frontend

    - name: Build backend
      run: npm run build:backend

    - name: Build frontend
      run: npm run build:frontend

  performance:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js 18.x
      uses: actions/setup-node@v4
      with:
        node-version: 18.x
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build project
      run: npm run build

    - name: Start backend
      run: |
        npm run build:backend
        cd backend && npm start &
        sleep 10

    - name: Seed test data
      run: npm run seed

    - name: Performance test
      run: |
        # Basic performance test
        curl -w "@curl-format.txt" -o /dev/null -s "http://localhost:3001/api/users?page=1&pageSize=50"
      env:
        CURL_FORMAT: "time_total: %{time_total}s\ntime_namelookup: %{time_namelookup}s\ntime_connect: %{time_connect}s\ntime_appconnect: %{time_appconnect}s\ntime_pretransfer: %{time_pretransfer}s\ntime_redirect: %{time_redirect}s\ntime_starttransfer: %{time_starttransfer}s\n"

